
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    # ✅ Fix permissions BEFORE checkout to avoid "Permission denied"
    - name: Fix ownership from previous runs
      run: |
        sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/k2k-iot-frontend || true
        sudo chmod -R u+rwX,go+rX /home/ubuntu/actions-runner/_work/k2k-iot-frontend || true
    - uses: actions/checkout@v4
      with:
        clean: true   # still wipe untracked files safely

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    - run: |
        touch .env
        echo "${{ secrets.ANTESOFE}}" > .env
    - name: Build React frontend
      run: NODE_OPTIONS="--max-old-space-size=3072" npm run build

    - name: Serve React build with PM2
      run: |
        pm2 delete FrontendServer || true
        pm2 serve build 8080 --name FrontendServer --watch
        pm2 save
