name: Frontend Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install frontend dependencies
    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    # Create .env file from secret
    - name: Setup environment
      run: |
        touch .env
        echo "${{ secrets.ANTESOFE }}" > .env

    # Fix permissions (important if self-hosted runner writes as root sometimes)
    - name: Fix permissions before build
      run: |
        sudo chown -R $USER:$USER .
        sudo chmod -R u+rwX,go+rX .

    # Build React frontend
    - name: Build frontend
      run: NODE_OPTIONS="--max-old-space-size=3072" npm run build

    # Serve with PM2
    - name: Serve React build with PM2
      run: |
        pm2 delete FrontendServer || true
        pm2 serve dist 8080 --name FrontendServer --spa
        pm2 save
